services:
  db-messages:
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: "db-messages"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messages
    volumes:
      - messages-db-vol:/var/lib/postgresql/data
  search-messages:
    image: quickwit/quickwit:latest
    ports:
      - "7280:7280"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7280/api/v1/version"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["run"]
    container_name: "search-messages"

volumes:
  messages-db-vol:
